### PR TITLE
Add Toastify Notifications for Relay Health and Events

### LINKED ISSUE #3: BOUNTY: Toastify Notifications
Use the 'Toastify' library to create notifications for users regarding relay health and new events.

The basic functionality for this is mostly implemented and it is mainly a UI/UX task of building unobtrusive and informative notifications in any media device context (desktop, tablet, mobile)

**Reward**
$100

### PR DESCRIPTION
**Pull request by rahat2134**
Implemented toastify notifications for relay health status and new events, providing unobtrusive and informative user feedback across all device contexts.

fix #3 

### Changes Made
- Added Toastify JS and CSS to index.html
- Implemented notifications for:
  - Relay connections (success/failure)
  - Relay disconnections
  - New events
  - Error handling
- Used different styles/colors for different notification types:
  - Success (green gradient)
  - Error (red gradient)
  - Events (blue gradient)
  - Disconnection (orange gradient)

### Features
- Auto-dismissing notifications
- Responsive design that works on all devices
- Clear visual hierarchy with different colors
- Non-intrusive positioning (top-right corner)
- Informative messages

### Files Changed
- `index.html`: Added Toastify CSS and JS
- `src/relay_pool/relay_pool.rs`: Added notifications for relay events
- `src/widgets/toastify/toastify.rs`: Added notification types and styling
- `src/widgets/toastify/mod.rs`: Updated module exports

Closes #3

### CODE REVIEW

**Comment by rahat2134** [comment]
@42Pupusas  PTAL

**Comment by 42Pupusas** [comment]
Hey @rahat2134 

- I created a small test component to check the notifications, and it doesn't look like the styling is applying correctly.

*Screenshot*
Screenshot from 2024-10-25 14-47-30
 
Maybe you can add the test component  to the PR and make sure the styling is being applied correctly?

```
#[function_component(ToastifyTest)]
pub fn toastify_test() -> Html {
    use_effect_with((), move |_| {
        let timeout = 6000;
        gloo_timers::callback::Interval::new(timeout, move || {
            yew::platform::spawn_local(async move {
                let login_options = ToastifyOptions::new_login("Login Notification".to_string());
                let logout_options = ToastifyOptions::new_relay_connected("Relay Connected");
                let options = ToastifyOptions::new_success("Success Notification");
                let options2 = ToastifyOptions::new_relay_error("Error Notification");
                let options3 = ToastifyOptions::new_relay_disconnected("Relay Disconnected");
                let options4 = ToastifyOptions::new_event_received("Event Received");
                let interval = std::time::Duration::from_secs(1);
                login_options.clone().show();
                gloo_timers::future::sleep(interval).await;
                logout_options.clone().show();
                options.clone().show();
                gloo_timers::future::sleep(interval).await;
                options2.clone().show();
                gloo_timers::future::sleep(interval).await;
                options3.clone().show();
                gloo_timers::future::sleep(interval).await;
                options4.clone().show();
                gloo_timers::future::sleep(interval).await;
            });
        })
        .forget();
        || {}
    });
    html! {
        <div>
            <h1>{"Toastify Test"}</h1>
            <p>{"Notifications will play on a loop"}</p>
        </div>
    }
}
```

**Comment by 42Pupusas** [comment]
One thing to consider is the notification about the relay pool being disconnected should not auto dismiss, because the user should refresh the app for it to work correctly at that point.

**Comment by 42Pupusas** [comment]
I pushed some upgrades today that simplifies the relay pool logic so you might need to make some changes also.

**Comment by rahat2134** [comment]
@42Pupusas PTAL, I have done the required changes!!
Screenshot 2024-10-27 at 12 22 05 AM
Screenshot 2024-10-27 at 12 22 09 AM

**Comment by 42Pupusas** [comment]
Great work @rahat2134 

Please comment your BTC address here. Once the bounty reward has been paid I will post transaction ID here for transparency.

**Pull request merged**
