### PR TITLE
Leaflet Widget Library Coverage and Real-time Geotracking

### LINKED ISSUE #2: BOUNTY: Coverage for widget library bindings and options
We are using several open source libraries to provide widget components. The WASM bindings and options are very incomplete and coverage needs to be improved. 

Coverage of libraries should at least include: 

- All initial option object configurations
- All event types
- Demo of Yew functional components showcasing Nostr integration

### PR DESCRIPTION
**Pull request by rahat2134**
Fixes #2 - Leaflet
This PR implements:
1. Leaflet map integration with working bindings
2. Real-time geotracking using Nostr events
3. Location detection and display

Changes:
- Added component.rs for Leaflet component
- Updated mod.rs for proper exports
- Uses existing leaflet.rs bindings
- Uses nominatim.rs for location names

Features:
- Interactive map with zoom/pan controls
- Real-time location updates
- Nostr event integration (kind 27235)
- Location name display

Tested:
- Map loads and displays correctly
- Location detection works
- Zoom/pan controls functional
- Nostr event integration verified

### CODE REVIEW

**Comment by rahat2134** [comment]
@42Pupusas PTAL! I am open to any feedback.

**Comment by 42Pupusas** [comment]
This is a good start but there are a few things I would like to see before marking completed.

- Bindings for zoom and pane Leaflet API functions  
- Bindings for Geolocation methods of the Leaflet API
- `Structs` for map and marker options (currently just passing in an empty object)
- Custom Icon support

**Comment by 42Pupusas** [comment]
I am not seeing the markers that should be added with the test button, maybe review the logic there?

image

**Comment by 42Pupusas** [comment]
The `LeafletComponent` should be more generic so it can be applied to different use cases. I think a better approach would be to pass these variables as props so other components can interact with the map and marker state: 
```
    let map_id = "leaflet-map";
    let map = use_state(|| None::<LeafletMap>);
    let marker = use_state(|| None::<Marker>);
    // Maybe this can be the nominatim object instead?
    let location_name = use_state(|| String::new());

```
 There could also be many markers so maybe a Vec<markers> makes more sense for the state.

**Comment by rahat2134** [comment]
[screen-capture.webm](https://github.com/user-attachments/assets/8780ff6c-1a9d-4640-832b-9916c0403713)

@42Pupusas PTAL to the video when you have some free time. Thanks :)
Try to implement the changes. Do they look good?

**Comment by 42Pupusas** [comment]
I tested the changes to the demo component and it works great. However, I would still think we need to do what I described above:

> The `LeafletComponent` should be more generic so it can be applied to different use cases. I think a better approach would be to pass these variables as props so other components can interact with the map and marker state:
> 
> ```
>     let map_id = "leaflet-map";
>     let map = use_state(|| None::<LeafletMap>);
>     let marker = use_state(|| None::<Marker>);
>     // Maybe this can be the nominatim object instead?
>     let location_name = use_state(|| String::new());
> ```
> 
> There could also be many markers so maybe a Vec makes more sense for the state.

**Comment by rahat2134** [comment]
1. Made `LeafletComponent` more generic and reusable by:
   - Making markers state a Vec to support multiple markers
   - Added props for customization:
     ```rust
     pub struct Props {
         pub map_id: AttrValue,
         pub on_map_created: Callback<LeafletMap>,
         pub on_marker_created: Callback<Marker>,
         pub on_location_changed: Callback<GeolocationCoordinates>,
         pub on_location_name_changed: Callback<String>,
         pub markers: Vec<(f64, f64)>,
         pub initial_zoom: Option<u8>,
         pub show_location_name: bool,
         pub class: Classes,
         pub style: Option<AttrValue>,
     }
     ```

2. Fixed all major functionality:
   - Initial location loading works ✅
   - Send Test Location works ✅ 
   - Location tracking works ✅
   - Zoom controls work ✅
   - Multiple markers support ✅

3. Added proper error handling and debugging

**Comment by rahat2134** [comment]
@42Pupusas PTAL, Everything is working. I tried to stick to your feedback.
[Video Proof](https://github.com/user-attachments/assets/6c8f5246-942e-4131-bf42-d9db13547d84)

**Comment by 42Pupusas** [comment]
Reviewed and everything works great!

Amazing stuff !

**Pull request merged**
